### ISSUE TITLE
Duplicate A record is possible

### ISSUE THREAD

**Issue by c1784497** [msimerson/NicTool#185]
### NicTool version
2.34
### perl version
5.18.2-2ubuntu1.1
### OS version
Ubuntu 14.04.5
### Expected behavior
Duplicate record error
### Observed behavior / Steps to reproduce
![testa](https://cloud.githubusercontent.com/assets/6068155/24917135/79f1b348-1edc-11e7-9908-228f728fbc3b.png)

**Comment by msimerson** [comment]
Oops, that's fixed now.

**Comment by c1784497** [comment]
In the current master branch this issue still exists. I do the same test as described [here](https://github.com/msimerson/NicTool/issues/185#issue-220991213). I can't find the reason why this is possible.
